//
//  WindowRecords.swift
//  Loop
//
//  Created by Kai Azim on 2023-09-23.
//

import Scribe
import SwiftUI

@Loggable(style: .static)
enum WindowRecords {
    private static var recordsByWindowID: [CGWindowID: WindowRecords.Record] = [:]

    struct Record {
        let initialFrame: CGRect
        var actions: [WindowAction]

        init(initialFrame: CGRect) {
            self.initialFrame = initialFrame
            self.actions = [.init(.initialFrame)]
        }
    }

    /// Erase all previous records for a window
    /// - Parameter window: Window to erase
    static func eraseRecords(for window: Window) {
        guard recordsByWindowID[window.cgWindowID] != nil else {
            // Records don't exist
            return
        }

        recordsByWindowID[window.cgWindowID] = nil
        log.success("Erased records for: \(window)")
    }

    static func recordFirstIfNeeded(for window: Window) {
        guard recordsByWindowID[window.cgWindowID] == nil else { return }
        recordsByWindowID[window.cgWindowID] = Record(initialFrame: window.frame)
        log.info("Recorded first for: \(window)")
    }

    /// Determines if an action should be recorded using its frame instead of the action applied onto it.
    /// - Parameter action: the action to apply onto the window.
    /// - Returns: Whether this action should be recorded with its final frame instead of using the action.
    static func shouldStoreAsFinalFrame(_ action: WindowAction) -> Bool {
        // Actions that are stored as frames need to be recorded *after* resize.
        // These actions are context-dependent, and cannot simply be called as an action to restore the previous state.
        let storeAsFrame = action.direction.willChangeScreen || action.willManipulateExistingWindowFrame
        return storeAsFrame
    }

    /// Record a window's action in the records array
    /// - Parameters:
    ///   - window: Window to record
    ///   - action: WindowAction to record
    static func record(_ window: Window, _ action: WindowAction) {
        // If the window has not been recorded, record it
        recordFirstIfNeeded(for: window)

        // There is no point in recording undo
        guard action.direction != .undo else {
            return
        }

        if shouldStoreAsFinalFrame(action), let screen = ScreenUtility.screenContaining(window) {
            let customActionName = "autogenerated_record_\(action.getName())"
            let windowFrame = window.frame
            let adjustedBounds = PaddingConfiguration
                .getConfiguredPadding(for: screen)
                .applyToBounds(screen.cgSafeScreenFrame)

            let proportionalSize = CGRect(
                x: (windowFrame.minX - adjustedBounds.minX) / adjustedBounds.width,
                y: (windowFrame.minY - adjustedBounds.minY) / adjustedBounds.height,
                width: windowFrame.width / adjustedBounds.width,
                height: windowFrame.height / adjustedBounds.height
            )

            let action = WindowAction(
                .custom,
                keybind: [],
                name: customActionName,
                unit: .percentage,
                anchor: nil,
                width: proportionalSize.width * 100,
                height: proportionalSize.height * 100,
                xPoint: proportionalSize.minX * 100,
                yPoint: proportionalSize.minY * 100,
                positionMode: .coordinates,
                sizeMode: .custom
            )

            recordsByWindowID[window.cgWindowID]?.actions.insert(action, at: 0)
        } else {
            recordsByWindowID[window.cgWindowID]?.actions.insert(action, at: 0)
        }

        log.info("Recorded: \(action) for: \(window)")
    }

    /// Removes the last action performed on the specified window. This will NOT remove the first action for the specified window.
    static func removeLastAction(for window: Window) {
        guard let record = recordsByWindowID[window.cgWindowID],
              record.actions.count > 1
        else {
            log.info("Skipped removing last record for: \(window)")
            return
        }

        recordsByWindowID[window.cgWindowID]?.actions.removeFirst()

        log.info("Removed last record for: \(window)")
    }

    /// This window's last action
    /// - Parameters:
    ///   - window: Window to check
    /// - Returns: The window action
    static func getLastAction(for window: Window) -> WindowAction? {
        guard let record = recordsByWindowID[window.cgWindowID],
              record.actions.count >= 2
        else {
            return nil
        }

        return record.actions[1]
    }

    /// This window's current recorded action
    /// - Parameters:
    ///   - window: Window to check
    /// - Returns: The window action
    static func getCurrentAction(for window: Window) -> WindowAction? {
        guard let record = recordsByWindowID[window.cgWindowID],
              record.actions.count >= 1
        else {
            return nil
        }

        return record.actions[0]
    }

    static func getInitialFrame(for window: Window) -> CGRect? {
        recordsByWindowID[window.cgWindowID]?.initialFrame
    }
}
