name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/swiftformat.yml'
      - '.swiftformat.yml'
      - '**/*.swift'

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v5

      - name: 🎨 SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log
